### PR TITLE
User functionality ng

### LINKED ISSUE #1: Check current User functionality
A User holds on to all of a user’s data. As a user, I should be able to:

- [x] Favorite recipes (add to / remove from the user’s favoriteRecipes)
- [x] Decide to cook a recipe that week (add to my recipesToCook)
- [x] Filter my favoriteRecipes or recipesToCook by type
- [x] Search any of my saved recipes by name or ingredient
- [x] All required methods are present
- [x] All required properties are present

### LINKED ISSUE #6: User - Favorite Recipes
User should be able to add/remove a recipe from their "favoriteRecipes"

Favorites are meant to be recipes that one can easily find again. When a user decides to cook a recipe, they should be able to determine whether they have sufficient ingredients in their pantry (see Pantry user stories). If they do not, they should be able to see a list of what ingredients they need to buy, and how much it will cost. User should be able to do this for at least one recipe. Making a list of recipesToCook can be implemented at a later time.

### LINKED ISSUE #9: User - Deciding to cook recipe
A user should be able to add a recipe to their 'recipes to cook'

### LINKED ISSUE #11: User - Filter
User should be able to filter their 'favorite recipes'  or 'recipes to cook' by type

### LINKED ISSUE #13: User - Search
Users should be able to search through any saved recipes by name or ingredient

### PR DESCRIPTION
**Pull request by nicolegooden**
## Description

+ I have completed the test suite for `User`, which covers all properties, required methods, etc.  Some unit tests have been updated as well as created.

+ The `user.js` implementation file has been updated, and all included code has passed the 21 tests from `user-test.js`.

## Affected areas of application

+ user.js
+ user-test.js

**No UI has been affected by these changes**

## How Has This Been Tested?

+ This has been tested with `npm test` in the terminal, and each test is failable.

- `user-test.js`

## Relevant Tickets

Closes #1 
Closes #6 
Closes #9 
Closes #13 
Closes #11 

## Screenshots

n/a

## Question

On issue 6, there is mention of the Pantry responsibilities and what the User should be able to find based on the user's pantry.  Is this covered in `Pantry`?

### CODE REVIEW

**Review by taylorjohnson141 — APPROVED** [review]
I really liked how dynamic your methods are as well as how in depth your methods are. I'm also glad you saw we had to add a new property on line 7 I feel that we would have ran into some trouble later on without it.

**Comment by CalebCyphers** [comment]
In answer to your question: Yes, the first piece of functionality in `pantry` is the ability to test wether or not there are enough ingredients to make a meal. This functionality will likely be tied directly to the 'expand recipe' button, which will run the 'doIHaveEnoughIngredients' method to populate the DOM

This is looking really clean. I'll import it into pantry.js for testing now. Thanks for finishing it up, and awesome use of granular tests.

**Review by CalebCyphers — APPROVED** [review]
Awesome tests, nice, clean code. Perhaps we can code in some small test datasets as a refactor.

**Comment by nicolegooden** [comment]
@CalebCyphers @taylorjohnson141 

Thanks for this feedback! I will work on using the smaller dataset (which I will create in `user-test.js`) as Caleb pointed out.  I have overlooked that part of the original test file!

**Pull request merged**
